# Generated by Django 2.0.2 on 2018-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_up_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
