# Generated by Django 2.0.2 on 2018-02-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180212_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
