# Generated by Django 2.0.2 on 2018-02-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180212_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='profile',
        ),
    ]
