# Generated by Django 2.0.2 on 2018-02-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180212_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='profile',
        ),
    ]
