# Generated by Django 2.0.2 on 2018-02-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_userfollow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollow',
            new_name='Follow',
        ),
    ]
