# Generated by Django 2.0.2 on 2018-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180221_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
