# Generated by Django 2.0.2 on 2018-04-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180225_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_daddu',
            field=models.BooleanField(default=False),
        ),
    ]
