# Generated by Django 2.0.2 on 2018-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_is_daddu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_daddu',
            field=models.BooleanField(default=True),
        ),
    ]
